theme: jekyll-theme-minimal
title: DJ Ikamon
description: A newcomer DJ ready to make the crowd move and jump to bassy house music. DJ Ika is not afraid to perform an eclectic blend of genres and make experimental choices that will get the audience moving like nobodies business.
